[[redirects]]
  from = "/yelpSearch/*"
  to = "https://api.yelp.com/v3/businesses/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/yelpCategories/"
  to = "https://api.yelp.com/v3/categories/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}